# Generated by Django 3.0.4 on 2020-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasegna',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
